apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketaka-auth
  namespace: argocd
spec:
  project: ticketaka
  source:
    repoURL: https://github.com/F1T4-HOTSUN/manifest.git
    targetRevision: HEAD
    path: resources/auth # 배포 관련 YAML 경로
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketaka-auth
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
